# Generated by Django 3.1.2 on 2023-11-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('addresse', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('Rental', 'rental'), ('Sale', 'sale')], max_length=200)),
                ('realty_type', models.CharField(choices=[('Office', 'office'), ('Land Plot', 'land plot'), ('Warehouse', 'warehouse'), ('Retail', 'retail'), ('Coworking', 'coworking')], max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('token', models.CharField(max_length=228)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
