version: '3'

services:
  mysite:
    build:
      context: ./mysite/
      dockerfile: ./Dockerfile
    command:  >
      sh -c "ls &&
             python manage.py makemigrations polls &&
             python manage.py migrate &&
             python manage.py loaddata sample.json &&
             python manage.py createsuperuser --noinput --username admin --email example@example.com
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgresql:
            condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresql
      - DB_NAME=main
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=bureauxlocaux123
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - PYTHONUNBUFFERED=True
      - DJANGO_SUPERUSER_PASSWORD=1234
    volumes:
      - ./mysite/:/mysite/
      
  postgresql:
    image: postgres:13.0
    volumes:
      - ./local_volumes/db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=bureauxlocaux123
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      